;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Actions.Attack.Heavy",DevComment="")
+GameplayTagList=(Tag="Actions.Attack.Light",DevComment="")
+GameplayTagList=(Tag="Actions.Attack.Sword",DevComment="")
+GameplayTagList=(Tag="Actions.Attack.Sword.Combo1",DevComment="")
+GameplayTagList=(Tag="Actions.Attack.Sword.Combo2",DevComment="")
+GameplayTagList=(Tag="Actions.Attack.Sword.Combo3",DevComment="")

